### ISSUE TITLE
Celery not starting

### ISSUE THREAD

**Issue by EBoisseauSierra** [unipartdigital/puppet-superset#8]
## Issue

It seems that Celery is not starting on puppet-managed instances. This notably cause screenshot in tiles not to display correctly:

![Screenshot from 2021-05-24 12-49-41](https://user-images.githubusercontent.com/37387755/119343570-89e81b80-bc8e-11eb-8d49-18412ce4cdd2.png)

## Details

```
[fedora@instance_url ~]$ sudo puppet agent --test --environment amc 2>&1 | grep -v vendor
Info: Using configured environment 'amc'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for instance_url
Info: Applying configuration version '1621245331'
[…]
Notice: Applied catalog in 1.12 seconds
[fedora@instance_url ~]$ sudo systemctl status celery
● celery.service - Celery Service
     Loaded: loaded (/etc/systemd/system/celery.service; enabled; vendor preset: disabled)
     Active: activating (start) since Mon 2021-05-17 10:55:37 BST; 24ms ago
Cntrl PID: 1497944 (celery)
      Tasks: 1 (limit: 4680)
     Memory: 2.9M
        CPU: 20ms
     CGroup: /system.slice/celery.service
             └─1497944 /opt/superset/venv/bin/python3.8 /opt/superset/venv/bin/celery -A superset.tasks.celery_app multi start worker1 --pidfile=/var/run/celery/%n.pid --logfile=/var/log/celery/%n%I.log --loglevel=DEBUG --pool=prefork -O fair --concurrency=4

May 17 10:55:37 instance_url systemd[1]: Starting Celery Service...
[fedora@instance_url ~]$ /opt/superset/venv/bin/python3.8 /opt/superset/venv/bin/celery -A superset.tasks.celery_app multi start worker1 --pidfile=/var/run/celery/%n.pid --logfile=/var/log/celery/%n%I.log --loglevel=DEBUG --pool=prefork -O fair --concurrency=4
logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/opt/superset/venv/lib64/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
celery multi v4.4.7 (cliffs)
Traceback (most recent call last):
  File "/opt/superset/venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/celery.py", line 491, in handle_argv
    return self.execute(command, argv)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/celery.py", line 335, in run_from_argv
    return cmd.execute_from_commandline([command] + argv)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 272, in execute_from_commandline
    return self.call_command(argv[0], argv[1:])
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 279, in call_command
    return self.commands[command](*argv) or EX_OK
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 149, in _inner
    return fun(self, *args, **kwargs)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 157, in _inner
    return fun(self, self.cluster_from_argv(argv), **kwargs)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 367, in cluster_from_argv
    _, cluster = self._cluster_from_argv(argv, cmd=cmd)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/bin/multi.py", line 372, in _cluster_from_argv
    return p, self.Cluster(list(nodes), cmd=cmd)
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/apps/multi.py", line 302, in <genexpr>
    self._node_from_options(
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/apps/multi.py", line 311, in _node_from_options
    return Node(nodename, cmd, append,
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/apps/multi.py", line 135, in __init__
    self.options = self._annotate_with_default_opts(
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/apps/multi.py", line 143, in _annotate_with_default_opts
    self._setdefaultopt(options, ['--pidfile', '-p'], '/var/run/celery/%n.pid')
  File "/opt/superset/venv/lib64/python3.8/site-packages/celery/apps/multi.py", line 157, in _setdefaultopt
    os.makedirs(dir_path)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/run/celery'
[fedora@instance_url ~]$ sudo systemctl start celery
Job for celery.service failed because the control process exited with error code.
See "systemctl status celery.service" and "journalctl -xe" for details.
```

**Comment by EBoisseauSierra** [comment]
We haven't been able to reproduce when running puppet again ￫ closing for now.
